>>> from apps.user_login.models import *
>>> Users.objects.create(first_name="Salvador", last_name="Dali", email="salvador@dali.com", age=78)
<Users: Users object>
>>> >>> Users.objects.create(first_name="Marty", last_name="McFly", email="marty85@hillvalley.com", age=17)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Users' has no attribute 'ors'
>>> Users.objects.all()
<QuerySet [<Users: Users object>]>
>>> Users.objects.create(first_name="Marty", last_name="McFly", email="marty85@hillvalley.com", age=17)
<Users: Users object>
>>> Users.objects.all()
<QuerySet [<Users: Users object>, <Users: Users object>]>
>>> Users.objects.all().first_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'QuerySet' object has no attribute 'first_name'
>>> Users.objects.last().last_name
u'McFly'
>>> Users.objects.first().first_name
u'Salvador'
>>> Users.objects.create(first_name="Marie", last_name="Curie", email="mariecurie@radium235.com", age=43)
<Users: Users object>
>>> Users.objects.create(first_name="Ruth Bader", last_name="Ginsberg", email="notoriousRBG@doj.gov", age=88)
<Users: Users object>
>>> Users.objects.first()
<Users: Users object>
>>> Users.objects.first()
<Users: Users object>
>>> Users.objects.first().__repr__()
'<Users: Users object>'
>>> Users.objects.first()
<Users: Users object>
>>> Users.objects.first().first_name
u'Salvador'
>>> Users.objects.all().first_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'QuerySet' object has no attribute 'first_name'
>>> Users.objects.count()
4
>>> Users.objects.filter(first_name="Marty")
<QuerySet [<Users: Users object>]>
>>> Users.objects.__str__
<bound method Manager.<lambda> of <django.db.models.manager.Manager object at 0x10e8f8a10>>
>>> Users.objects.order_by("first_name")
<QuerySet [<Users: Users object>, <Users: Users object>, <Users: Users object>, <Users: Users object>]>
>>> Users.objects.order_by("first_name").first_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'QuerySet' object has no attribute 'first_name'
>>> Users.objects.first()
<Users: Users object>
>>> Users.objects.get(id=3).first_name
u'Marie'
>>> Users.objects.all('first_name')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: all() takes exactly 1 argument (2 given)
>>> Users.objects.all(first_name)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'first_name' is not defined
>>> Users.objects.first_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Manager' object has no attribute 'first_name'
>>> Users.objects.first().first_name
u'Salvador'
>>> Users.objects.first().first_name = "Dolly"
>>> Users.objects.first().first_name
u'Salvador'
>>> Users.objects.first().save()
>>> Users.objects.first().first_name
u'Salvador'
>>> Users.objects.first().first_name = "Dolly"
>>> Users.objects.first().save()
>>> Users.objects.first().first_name
u'Salvador'
>>> b = Users.objects.first()
>>> b.first_name = "Walter"
>>> b.save()
>>> b.first_name
'Walter'
>>> Users.objects.first().first_name
u'Walter'
>>> Users.objects.first().last_name
u'Dali'
>>> Users.objects.first().age
78
>>> Users.objects.get(id=1).last_name
u'Dali'
>>> Users.objects.get(id=1).last_name.delete
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'unicode' object has no attribute 'delete'
>>> Users.objects.get(id=1).delete
<bound method Users.delete of <Users: Users object>>
>>> Users.objects.get(id=1).last_name
u'Dali'
>>> Users.objects.get(id=1).delete()
(1, {u'user_login.Users': 1})
>>> Users.objects.get(id=1).last_name
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/johnnyfive/Desktop/DojoAssignments/myEnvironments/djangoEnv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/johnnyfive/Desktop/DojoAssignments/myEnvironments/djangoEnv/lib/python2.7/site-packages/django/db/models/query.py",line 385, in get
    self.model._meta.object_name
DoesNotExist: Users matching query does not exist.
>>> Users.objects.count()
3
>>> Users.objects.get(id=2).delete()
(1, {u'user_login.Users': 1})
>>> Users.objects.count()
2